### ISSUE TITLE
Unable to get gltf models displayed on map

### ISSUE THREAD

**Issue by BS666** [3dcitydb/3dcitydb-web-map#31]
Hi,
I am trying to get the LoD2 example data of https://geobroker.geobasis-bb.de/gbss.php?MODE=GetProductInformation&PRODUCTID=0414a37a-a749-4ee6-9f59-a41226919c58 in web-map working - but unfortunately l can only see the rectangle of bounding box border.
Is this a bug/misconfiguration /corrupt material? I'm lost on that one.
Works fine with Google Earth Pro.

My Settings are based on default except:
KML/COLLADA/glTFExport:General:Show bounding box borders [X]
KML/COLLADA/glTFExport:General:Write JSON file [X]
General:Logging:Console:Log level "DEBUG"

I did following:
- Imported LoD2 data into PostGIS (EPSG:25833)
- Exported to COLLADA/glTF visible from 0 
  - Bounding Box 369194.628:5805164.942, 369283.314:5805275.978 (created by Database => Bounding box)
  - Automatic tiling
  - LoD2
  - All Objects
- Result:
[13:47:02 INFO] Initializing database export... 
[13:47:02 INFO] Checking for spatial indexes on geometry columns of involved tables...
[13:47:02 INFO] 1 (1x1x1) tiles will be generated.
[13:47:02 INFO] Exporting to file: /.../test6/Tiles/0/0/test_Tile_0_0_collada.kml
[13:47:02 DEBUG] 268 candidate objects found for Tile_0_0.
[13:47:02 INFO] Exported CityGML features:
[13:47:02 INFO] BUILDING: 7
[13:47:02 INFO] Processed geometry objects: 246
[13:47:02 INFO] Total export time: 00 s.
[13:47:02 INFO] Database export successfully finished.
- Unfortunately converting to glTF does not work inside 3D City Database Importer/Exporter. There are no error message but no glTF files as well. 
Therefore I converted all files by COLLADA2glTF (latest version) by myself (default options)
- Added Layer to web-map with only MasterJSON and name provided

Result:
- added successfully (?) - But only bounding box border is visible
- No errors in console
- test_Tile_0_0_collada.kml file processed
- gltf files processed
- found glTF models in _cesiumviewer._dataSourceCollection._dataSource
- tested with Vivaldi, Firefox

**Comment by Son-HNguyen** [comment]
Hi @BS666 

did you see any errors or warnings in the browser while running the web map? Could you provide us the glTF you exported?

Best,
Son

**Comment by BS666** [comment]
Hi @Son-HNguyen 

[3dcitydb-web-map-test.tar.gz](https://github.com/3dcitydb/3dcitydb-web-map/files/1982529/3dcitydb-web-map-test.tar.gz)

thx in advance

**Comment by Son-HNguyen** [comment]
Hi @BS666 

your glTF files seem to produce incorrect results on the web map, but I could still see the buildings (not only the bouding box).

I used the CityGML file in the link you provided and exported again and this is what I have on my computer:
![image](https://user-images.githubusercontent.com/5765503/39760728-688131a4-52d6-11e8-83dc-a90c9864f793.png)

I guess the problem was somewhere while you were exporting the building. Follow [our tutorial here](https://github.com/3dcitydb/tutorials/blob/master/3DCityDB_V3.3_Hands-On_Tutorial.pdf) and you should be able to get the same results.

Best,
Son

**Comment by CristinaIT** [comment]
Hello,
I have the same kind of problem with a LOD3 CityGML file.
When I try to display my KML model in the web-map-client I can see only the blue bounding box.
The file is defined with EPGS:32632 and works fine on google earth.
Any suggestion?

You will find the exported file here attached.

Thank you in advance,
Cristina.

![cattura](https://user-images.githubusercontent.com/43606244/48763072-b4ffe780-ecac-11e8-9735-509ccaa99ae8.JPG)

[UNIPV.zip](https://github.com/3dcitydb/3dcitydb-web-map/files/2598943/UNIPV.zip)

**Comment by Son-HNguyen** [comment]
What errors were shown in the developer mode in your browser?

I was able to visualize your provided data set without any problems (see picture).
![image](https://user-images.githubusercontent.com/5765503/49018330-6dd19500-f18b-11e8-8d84-9b0ff4951a45.png) Make sure the KML/COLLADA/glTF files and the web client are hosted on the same domain or use a proxy server to start the web client, otherwise you'd probably run into CORS problems (see #9, #26, #33, #39).

**Comment by CristinaIT** [comment]
Thank you for your answer.
From the developer console in the browser it seems that it fails to load the Tails even though they are in the same directory where the json file is.
I have already checked the CORS related problem and I should have solved it with reference to #39.
I will keep trying!

**Comment by Son-HNguyen** [comment]
Closed. Feel free to reopen if you still have any issues.
