### ISSUE TITLE
Issues with retireval and visualisation of attributes

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb-web-map#56]
Hi!

I am retrieving attributes via PostgREST. Some issues I have notices in the current version (1.8.3):

1) The labels (and associated behavious) seem inverted: you choose horizontal, and you get a vertical view (see attached images).

2) The vertical (i.e. horizontal) one seems broken (see example).

![Annotation1](https://user-images.githubusercontent.com/15018017/82313181-5104cf00-99c8-11ea-8bd2-9b620b4c6089.jpg)

![Annotation2](https://user-images.githubusercontent.com/15018017/82313186-52ce9280-99c8-11ea-805d-c14161fb1722.jpg)

**Comment by Son-HNguyen** [comment]
You can fetch the JSON response directly from the browser using for example the following URL:
`http://<HOST>/<TABLE>?gmlid=eq.<GMLID>`
where `<HOST>`, `<TABLE>` and `<GMLID>` should be replaced by corresponding values.

**Comment by gioagu** [comment]
Hi,

the JSON response is:

[{"gmlid":"PandID_0363100012233523","address":"Hobbemakade 6","postcode":"1071XK","class":"Non-residential (multi-function)","bag_function":null,"usage":"Kantoor; Opslag / Distributie; Recreatie / Sportcentrum","year_of_construction":1912,"measured_height":"13.36 m","bag_footprint_area":"1814 m^2","ahn3_gross_volume":"24234 m^3"}]

It's coming from a view exposed via PostgREST.

BR

**Comment by Son-HNguyen** [comment]
It seems that you have a "horizontal" table hosted by PostgREST (all object attributes in one row), so by selecting the table type `All object attributes in one row`, such JSON responses can be displayed correctly. Selecting the table type `One row per object attribute` would result in an error, since the table type here is incompatible. Note that the two options `All object attributes in one row` and `One row per object attribute` both refer to the structure of the tables stored in PostgreSQL and not how they are displayed in the web client.

**Comment by gioagu** [comment]
Thanks for the explanation, this is a detail I had completely missed.
