### ISSUE TITLE
Connect to Cesium?

### ISSUE THREAD

**Issue by GiuliaSpi** [3dcitydb/3dcitydb-web-map#59]
Hello everyone, 
I need a suggestion. I would like to reproduce this kind of filters (see image) inside 3dwebclient, is that possible? 
![image](https://user-images.githubusercontent.com/48022581/94922906-4e100400-04bb-11eb-9089-1f6f7cd52f77.png)
https://demos.cesium.com/NewYork/?view=-74.01434315131563%2C40.695538271606274%2C911.0269385112978%2C20.314857971210465%2C-32.080897112325566%2C0.07807235685294786
Anyone knows how can i do? Also, once finished my Scene, i would like tho generate the link and share it but all is connect with the local host, also with the RESTAPI local host 3000. Any suggest? 
Thank you

**Comment by Son-HNguyen** [comment]
Hi, there is currently no built-in filtering like that in the web client. But you could use multiple layers with different colors, etc.

When finish, simply click the button "Generate Scene Link" in the toolbox on the left of the screen, see https://github.com/3dcitydb/3dcitydb-web-map/issues/61#issuecomment-732126415.

In order to avoid `localhost` in the shared link, you should replace all the `localhost` instances in the layer with your domain name or IP address that are still visible to the people you'd like to share.
