### ISSUE TITLE
Save as Startup file

### ISSUE THREAD

**Issue by gkvoelkl** [3dcitydb/3dcitydb-web-map#61]
Hello,

your software works great. I can see all my tile layers.

Can I save my configuration in a file so that when starting the application again I will see my layers.

Now I have to configure the application every time I start it.

Thanks

Best regards Gerhard

**Comment by thomashkolbe** [comment]
The entire configuration can be saved in the URL as configuration parameters. Hence, when you open the URL, all layers and configuration options are automatically restored from the URL parameters.
In order to generate this link just open the "Toolbox" menu and click on "Generate Scene Link". This will create hyperlink that contains the entire configuration including the current camera position and information about activated and deactivated layers. The link can become quite long, but this does not seem to be a problem for modern browsers. You can then bookmark or share the link with others.

Hope this resolves your question
Best regards
Thomas Kolbe

**Comment by gkvoelkl** [comment]
Thanks for your quick answer.

I tested it and it works for me.
