### ISSUE TITLE
Failed to add new layer via localhost

### ISSUE THREAD

**Issue by kuramart** [3dcitydb/3dcitydb-web-map#73]
Hello,
I'm trying to visualize citygml data that I converted from Opendata sets. I am already using Importer and Exporter to export the KML file.
But when I try to load the generated kml file, an error occurs.

"Failed to load: http://localhost:8000/Users/Martin/Desktop/Kolada/Pokus/Budova_collada_MasterJSON.json"

My settings are as follows:
URL - http://localhost:8000/Users/Martin/Desktop/Kolada/Pokus/Budova_collada_MasterJSON.json
Name - Building_collada_MasterJSON.json
cityobjectsJsonUrl - http://localhost:8000/Users/Martin/Desktop/Kolada/Pokus/Budova.json

I tried all possible settings when selecting the layer data type. even the folder name combination.
![image](https://user-images.githubusercontent.com/88427467/157987877-515eb5e1-48df-4fb6-ba5e-124ce48fb825.png)
Thank you in advance for any reply.

**Comment by Son-HNguyen** [comment]
The MasterJSON file needs also to be available via HTTP for the browser to load. This file can be hosted using a wide range of servers, such as using NodeJS server as shown in our [documentation](https://3dcitydb-docs.readthedocs.io/en/latest/webmap/installation-config.html). Following this link, if you for example copy and paste the MasterJSON in the same folder as the file `index.html` with the path:
```
http://localhost:8000/3dwebclient/index.html
```
then you should be able to access the MasterJSON using this path
```
http://localhost:8000/3dwebclient/MasterJSON.json
```
This is just one example server you could use to host data. There are other options such as Apache, Express, etc. that are also very capable.

**Comment by BSchweiger** [comment]
Hello together,
I have the same problem. After exporting via the 3DCityDB-Importer-Exporter, I do not manage to load the locally saved kml-file. The file seems to be okay, since everthing works fine with Google Earth Pro. Also, the web map client is running fine on my local server.
 
Can you please explain in detail, how to load locally saved kml-files? I have stored both the kml and json file in the 3dwebclient-folder within the 3D-web-client-installation-folder (this took me many hours to find out). My settings are:

URL: http://localhost:8000/3dwebclient/xyz.kml
Name: xyz.kml
Layer data type: COLLADE/KML/gITF
KML clamp to ground
gITF version: 2.0
Thematic Data Source: Google ...
Table type: All object ...
All the other input boxes are empty.
  
As a result, I see the bounding box of my area, but no LoD2-buidlings within.

As far as I can see, the description of adding locally stored files - probably the most common application - is completely missing in the documentation.

Thank you very much in advance for your help!

**Comment by Son-HNguyen** [comment]
Make sure the option `KML clamp to ground` is activated or set the elevation of the globe correctly in case the KML models are hidden behind terrain. If the problem still persists, please paste the error you can find in the browser's console (using the developer mode). I've updated the documentation to reflect on how to publish locally stored files, see:
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/installation-config.html (note at the end of the page)
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/online-spreadsheet.html#importing-kml-gltf-models-with-thematic-data (table)

**Comment by BSchweiger** [comment]
Thank you for updating the documentation! I think, it is much clearer now.

**Comment by Son-HNguyen** [comment]
I hope that solved the issue. Closed. Feel free to reopen if the problem still persists.
