### ISSUE TITLE
Settings for showing thematic data using PostgREST

### ISSUE THREAD

**Issue by BSchweiger** [3dcitydb/3dcitydb-web-map#74]
Hi!

By trying to connect thematic data to the objects shown in the web map client, I never see any information: just "Loading feature information ..."
I have created a role as well as user in postgresql who have access and reading rigths to the LoD2 schema and all tables. PostgREST seems to work, since I get all the information using a terminal. 
The citygml-data was exported by the 3DCityDB Importer/Exporter as KML-files and is added 'successfully' from local storage as a layer in the web map client.

What information are needed to see thematic data in the web map client using PostgREST?

My - probably relevant - inputs look like this at the moment:
URL: http://localhost:8000/3dwebclient/xyz.kml
thematicDateUrl: http://localhost:3000/cityobject  - Which tables should I specify? Is it possible to state all tables? Do I have to enter curl, Invoke-RestMethod, etc.?
Thematic Data Source: PostgreSQL REST API
cityobjects.JsonUrl: http://localhost:8000/3dwebclient/zyx_MasterJSON.json

Thank you very much in advance!

**Comment by Son-HNguyen** [comment]
Hi,

the ``thematicDataUrl`` should point to the your table or view that you'd like to expose, for example:
```
https://example.com:3000/<table_name>
```

This table or view must be structured either as a "horizontal" or a "vertical" table and must have the correct order of columns and column names. Since most of the tables from the 3DCityDB are quite big for just some thematic fields in the web client, you could use a (materialized) view instead. This way you can define the order of the column and column names accordingly. Please refer to the documentation and the release notes for more information on the structure of these tables and views required in the web client:
https://3dcitydb-docs.readthedocs.io/en/latest/webmap/online-spreadsheet.html#
https://github.com/3dcitydb/3dcitydb-web-map/releases/tag/v1.9.0

To expose the table or view, you'd need a REST API or a web server. For example, for PostgreSQL, you could use PostgREST
https://postgrest.org/en/stable/ to publish your data (so that the web client can access to).

I hope that helps.
