### ISSUE TITLE
Database CRS for Web Map Client

### ISSUE THREAD

**Issue by ar-chad** [3dcitydb/3dcitydb-web-map#87]
Is there any specific CRS requirement for the database while exporting it to KML for visualisation on the Web Map Client? Does the database need to be in WSG84, in particular?

It is not mentioned in documentation of exporting for visualisation.

**Comment by thomashkolbe** [comment]
Hi,

if you just export to KML format, the CRS in the database can be arbitrary (if I remember correctly). During the export, an automatic coordinate system transformation to WGS84 will be made.

When you want to export the data to COLLADA / glTF format, then the data in the 3DCityDB must use a metric, cartesian
coordinate reference system, because each toplevel object (building, bridge etc.) will be simply translated to the origin (0,0,0)
and rotated around the z axis to reflect the north bearing. Then only the real world coordinate of that origin will be transformed and exported as the anchor point in WGS84 (as it is required for 3D COLLADA models embedded or referenced in KML files). If your dataset would not have been stored in the 3DCityDB using a metric, cartesian CRS, the objects visualized in e.g. Google Earth or Cesium would show up wrongly scaled.

Hence, if you want to export COLLADA or glTF-based visualization models, I recommend to use a local (e.g. national) projected and metric coordinate reference system for this. Do not use the pseudo mercator CRS (EPSG:3857) to store the data in the 3DCityDB, because it introduces strong errors (depending on where your models are in the world) with regard to the scaling of the 3D objects.

**Comment by thomashkolbe** [comment]
The [online documentation](https://3dcitydb-docs.readthedocs.io/en/latest/impexp/export-vis.html#) only provides shortened information about the visualization export compared to the earlier documentations we produced as a big PDF document. Here is the link to the last version of that document: [https://www.3dcitydb.org/3dcitydb/fileadmin/downloaddata/3DCityDB_Documentation_v4.2.pdf](https://www.3dcitydb.org/3dcitydb/fileadmin/downloaddata/3DCityDB_Documentation_v4.2.pdf). Check section 5.5 starting on page 167.

**Comment by ar-chad** [comment]
@thomashkolbe thank you for your answers. I successfully vis-exported to KML geometry from the database in 25833 and the model was placed correctly on the map. The vis-export process converted coordinates to WSG84 automatically.
